### ISSUE TITLE
Command line tool to build packages

### ISSUE THREAD

**Issue by Eeems** [toltec-dev/build#1]
We should have a command line abstractions to handle building packages. Right now you'll just have to know what docker container to run, and how to properly bind in the files and call the appropriate python scripts. Ideally I should just be in a directory with a package  file and call `toltec-build` or something, similar to `makepkg`. It should then spit out the ipk file(s) in the same directory.

**Comment by matteodelabre** [comment]
Just created toltec-dev/build (this repository) with an initial version of the standalone build tool. Usage is `toltecmk --work-dir [wdir] --dist-dir [ddir] [rdir]`, the following directories can be supplied:

* `wdir`: Working directory into which sources are fetched and builds are run. Can be safely discarded after build is complete. Default: `$PWD/build`.
* `ddir`: Directory into which final packages are put. Default: `$PWD/dist`.
* `rdir`: Directory where the recipe sources can be found. Should contain a `package` file. Default: `$PWD`.
