### ISSUE TITLE
Warn instead of error when custom fields are prefixed with _

### ISSUE THREAD

**Issue by Eeems** [toltec-dev/build#2]
https://github.com/toltec-dev/toltec/blob/testing/scripts/toltec/recipe.py#L433-L454

I think it would make more sense to warn in this scenario, and to provide a flag that you can use to force strict mode. This makes development annoying, as well as attempting to implement code scanners in the build process (I've been attempting to add https://github.com/github/codeql-action to oxide's build process).

**Comment by matteodelabre** [comment]
Fixed in 2ba8fdd592342f2c14e4ebcb77158e21a5396279. Non-prefixed custom fields will trigger the following warning:

```
[ WARNING] py.warnings: [RecipeWarning] /path/to/recipe: Unknown field 'custom_field'. Make sure to prefix the names of custom fields with '_'
```

Warnings can be silenced using the `-Wignore` flag or turned into errors with `-Werror`.
