### ISSUE TITLE
Consider using Nix to build the repo

### ISSUE THREAD

**Issue by NickHu** [toltec-dev/build#9]
Hi, I think this is a great effort within the reMarkable community, and it would be fantastic to have a central package store widely adopted. I noticed that that the `package` files are very similar to Arch Linux PKGBUILDs, and that they require docker and a bunch of shell scripts to build locally. I was wondering if anyone had considered using the [Nix](https://nixos.org/) package manager instead of this custom approach.

Nix has lots of advantages, especially if you care about reproducible builds, and it would be fairly straightforward to setup a development environment which 'just works' everywhere (without docker).

I know that this would be a huge undertaking, so I'm not expecting anything really, but I thought the discussion is still worth having.

I have seen some people already using nix with the remarkable tooling to great effect: https://github.com/pl-semiotics/nix-remarkable, and I think there might be some interest in this space.

CC @pl-semiotics @siraben

**Comment by Eeems** [comment]
Opkg does use opk files, but not with entware, which is what we have based our tools off of initially. My understanding is that they are the same format though, just a different file extension.

**Comment by Eeems** [comment]
I think we've agreed that this is out of scope for toltec. I'm closing the request.
